SET SEARCH_PATH to trabalho_g1;

ALTER TABLE cidade
ALTER COLUMN cod_cidade ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE cliente
ALTER COLUMN cod_cliente ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE periodicidade
ALTER COLUMN cod_periodicidade ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE tipo_espetaculo
ALTER COLUMN cod_tipo_espetaculo ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE estabelecimento
ALTER COLUMN cod_estabelecimento ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE espetaculo
ALTER COLUMN cod_espetaculo ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE sessao
ALTER COLUMN cod_sessao ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE reserva
ALTER COLUMN cod_reserva ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE pedido
ALTER COLUMN cod_pedido ADD GENERATED ALWAYS AS IDENTITY;